const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("piBot", {
  reportRendererStage: (stage) => ipcRenderer.send("pi:renderer-stage", stage),
  connect: () => ipcRenderer.invoke("pi:connect"),
  chooseFolder: (agentId) => ipcRenderer.invoke("pi:choose-folder", agentId),
  selectAgent: (agentId) => ipcRenderer.invoke("pi:select-agent", agentId),
  createAgent: (draft) => ipcRenderer.invoke("pi:create-agent", draft),
  updateAgent: (profile) => ipcRenderer.invoke("pi:update-agent", profile),
  archiveAgent: (agentId, archived) => ipcRenderer.invoke("pi:archive-agent", agentId, archived),
  deleteAgent: (agentId, deleteWorkspace) => ipcRenderer.invoke("pi:delete-agent", agentId, deleteWorkspace),
  trustWorkspace: (agentId) => ipcRenderer.invoke("pi:trust-workspace", agentId),
  newSession: () => ipcRenderer.invoke("pi:new-session"),
  openSession: (sessionPath, agentId) => ipcRenderer.invoke("pi:open-session", sessionPath, agentId),
  openScheduledSession: (jobId) => ipcRenderer.invoke("pi:open-scheduled-session", jobId),
  deleteSession: (sessionPath) => ipcRenderer.invoke("pi:delete-session", sessionPath),
  getSessions: (agentId) => ipcRenderer.invoke("pi:get-sessions", agentId),
  getScheduledJobs: () => ipcRenderer.invoke("pi:get-scheduled-jobs"),
  createScheduledJob: (draft) => ipcRenderer.invoke("pi:create-scheduled-job", draft),
  updateScheduledJob: (id, draft) => ipcRenderer.invoke("pi:update-scheduled-job", id, draft),
  setScheduledJobPaused: (id, paused) => ipcRenderer.invoke("pi:set-scheduled-job-paused", id, paused),
  runScheduledJob: (id) => ipcRenderer.invoke("pi:run-scheduled-job", id),
  deleteScheduledJob: (id) => ipcRenderer.invoke("pi:delete-scheduled-job", id),
  prompt: (message) => ipcRenderer.invoke("pi:prompt", message),
  abort: () => ipcRenderer.invoke("pi:abort"),
  setAgentModel: (agentId, key) => ipcRenderer.invoke("pi:set-agent-model", agentId, key),
  setSessionModel: (agentId, key) => ipcRenderer.invoke("pi:set-session-model", agentId, key),
  setThinkingLevel: (agentId, level) => ipcRenderer.invoke("pi:set-thinking-level", agentId, level),
  completeSetup: (accepted) => ipcRenderer.invoke("pi:complete-setup", accepted),
  setProviderApiKey: (providerId, apiKey, accepted) => ipcRenderer.invoke("pi:set-provider-api-key", providerId, apiKey, accepted),
  loginProvider: (providerId, type, accepted) => ipcRenderer.invoke("pi:login-provider", providerId, type, accepted),
  logoutProvider: (providerId) => ipcRenderer.invoke("pi:logout-provider", providerId),
  importPiAuth: (accepted) => ipcRenderer.invoke("pi:import-pi-auth", accepted),
  respondAuth: (promptId, value) => ipcRenderer.invoke("pi:auth-respond", promptId, value),
  cancelAuth: (promptId) => ipcRenderer.invoke("pi:auth-cancel", promptId),
  getTheme: () => ipcRenderer.invoke("pi:get-theme"),
  saveTheme: (theme) => ipcRenderer.invoke("pi:save-theme", theme),
  getUserProfile: () => ipcRenderer.invoke("pi:get-user-profile"),
  saveUserProfile: (profile) => ipcRenderer.invoke("pi:save-user-profile", profile),
  getWorkspacePreferences: (key) => ipcRenderer.invoke("pi:get-workspace-preferences", key),
  saveWorkspacePreferences: (key, preferences) => ipcRenderer.invoke("pi:save-workspace-preferences", key, preferences),
  listWorkspaceFiles: () => ipcRenderer.invoke("pi:list-workspace-files"),
  openWorkspaceFile: (path) => ipcRenderer.invoke("pi:open-workspace-file", path),
  revealWorkspaceFile: (path) => ipcRenderer.invoke("pi:reveal-workspace-file", path),
  openExternal: (url) => ipcRenderer.invoke("pi:open-external", url),
  onEvent: (listener) => {
    const handler = (_event, payload) => listener(payload);
    ipcRenderer.on("pi:event", handler);
    return () => ipcRenderer.removeListener("pi:event", handler);
  },
});
